# Generated by Django 4.2.11 on 2024-06-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blogApp/default.jpg', upload_to='blogApp/'),
        ),
    ]
